install.packages("readr")
library(readr)
refine_original <- read_csv("refine_original.csv")
refine_original <- mutate(refine_original, company = ifelse(company == "Phillips", "philips", company))
library(dplyr)
refine_original <- mutate(refine_original, company = ifelse(company == "Phillips", "philips", company))
refine_original <- mutate(refine_original, company = ifelse(company == "phillipS", "philips", company))
refine_original <- mutate(refine_original, company = ifelse(company == "phillips", "philips", company))
refine_original <- mutate(refine_original, company = ifelse(company == "Akzo","akzo",company))
refine_original <- mutate(refine_original, company = ifelse(company == "AKZO","akzo",company))
refine_original <- mutate(refine_original, company = ifelse(company == "akz0","akzo",company))
refine_original <- mutate(refine_original, company = ifelse(company == "ak zo","akzo",company))
refine_original <- mutate(refine_original, company = ifelse(company == "phllips", "philips", company))
refine_original <- mutate(refine_original, company = ifelse(company == "phillps", "philips", company))
refine_original <- mutate(refine_original, company = ifelse(company == "phillipS", "philips", company))
refine_original <- mutate(refine_original, company = ifelse(company == "Van Houten", "van houten", company))
refine_original <- mutate(refine_original, company = ifelse(company == "van Houten", "van houten", company))
refine_original <- mutate(refine_original, company = ifelse(company == "Unilever", "unilever", company))
refine_original <- mutate(refine_original, company = ifelse(company == "unilver", "unilever", company))
library(tidyr)
refine_original %>% separate(`Product code / number`, c('product_code', 'product number', sep="-"))
library(tidyselect)
refine_original %>% separate(`Product code / number`, c('product_code', 'product number', sep="-"))
library(tidyselect)
refine_original <- strsplit(`Product code / number`, c('product_code', 'product number', sep="-"))
refine_original %>% separate(`Product code / number`, c('product_code', 'product number', sep="-"))
refine_original <- mutate(refine_original, product_code = ifelse(product_code == "p", "Smartphone", product_code)) 
refine_original %>% separate(`Product code / number`, c('product_code', 'product_number', sep='-'))
separate(`Product code / number`, c('product_code', 'product_number', sep="-"))
refine_original %>% separate(refine_original, `Product code / number`, c('product_code', 'product number', sep="-"))
refine_original %>% separate(`Product code / number`, c('product_code', 'product_number'))
refine_original <- mutate(refine_original, product_code = ifelse(product_code == "p", "Smartphone", product_code))
refine_clean <- separate(refine_original, col = `Product code / number`, c('product_code', 'product_number'))
refine_clean
refine_clean <- mutate(refine_clean, product_code = ifelse(product_code == "p", "Smartphone", product_code))
refine_clean
refine_clean <- mutate(refine_clean, product_code = ifelse(product_code == "v", "TV", product_code))
refine_clean <- mutate(refine_clean, product_code = ifelse(product_code == "x", "Laptop", product_code))
refine_clean <- mutate(refine_clean, product_code = ifelse(product_code == "q", "Tablet", product_code))
refine_clean_a <- unite(refine_clean, col = "full_address", address, city, country, sep = ",")
refine_clean_b <- dummy_cols(refine_clean_a, select_columns = "company")
refine_clean_b <- data_frame(company_philips, company = ifelse(company == "philips",1,0))
library(dummy
      )
refine_clean_b <- dummy_cols(refine_clean_a, select_columns = "company")
refine_clean_b$companies_philips <-ifelse(company == "philips",1,0)
refine_clean_b$companies_philips <-data_frame(refine_clean_a, company=ifelse(company == "philips",1,0))
refine_clean_b$companies_philips <- if(refine_clean_a, company = ifelse(company == "philips",1,0))
refine_clean_b$companies_philips <-if(company == "philips"{print(1) } else {print(0)})
data(refine_clean_a)
data(refine_clean)
datadf$category <- ifelse(df$food %in% veg, "vegetable", df$food)(refine_original)
refine_clean_a$company_philips <- ifelse(refine_clean_a$company %in% "philips", 1, 0)
refine_clean_a$company_akzo <- ifelse(refine_clean_a$company %in% "akzo", 1, 0)
refine_clean_a$company_van_houten <- ifelse(refine_clean_a$company %in% "van houten", 1, 0)
refine_clean_a$company_unilever <- ifelse(refine_clean_a$company %in% "unilever", 1, 0)
refine_clean_a$product_laptop <- ifelse(refine_clean_a$product_code %in% "Laptop", 1, 0)
refine_clean_a$product_smartphone <- ifelse(refine_clean_a$product_code %in% "Smartphone", 1, 0)
refine_clean_a$product_tv <- ifelse(refine_clean_a$product_code %in% "TV", 1, 0)
refine_clean_a$product_tablet <- ifelse(refine_clean_a$product_code %in% "Tablet", 1, 0)
